DO $$
DECLARE
    tid UUID := '019b368e-b3ab-7212-8122-409d91a3befc';
    sid UUID := '019b367b-68f5-7c0c-b100-08a3e8dcc5a1';
    qid UUID;
BEGIN
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'log10(1000) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'3',true,qid),(gen_random_uuid(),'2',false,qid),(gen_random_uuid(),'4',false,qid),(gen_random_uuid(),'10',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'sin(90) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'1',true,qid),(gen_random_uuid(),'0',false,qid),(gen_random_uuid(),'-1',false,qid),(gen_random_uuid(),'0.5',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'cos(0) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'1',true,qid),(gen_random_uuid(),'0',false,qid),(gen_random_uuid(),'-1',false,qid),(gen_random_uuid(),'0.5',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'5! = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'120',true,qid),(gen_random_uuid(),'60',false,qid),(gen_random_uuid(),'24',false,qid),(gen_random_uuid(),'720',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'(2^3)^2 = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'64',true,qid),(gen_random_uuid(),'32',false,qid),(gen_random_uuid(),'128',false,qid),(gen_random_uuid(),'16',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'cbrt(27) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'3',true,qid),(gen_random_uuid(),'9',false,qid),(gen_random_uuid(),'6',false,qid),(gen_random_uuid(),'4',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'2^8 = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'256',true,qid),(gen_random_uuid(),'128',false,qid),(gen_random_uuid(),'512',false,qid),(gen_random_uuid(),'64',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'17^2 = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'289',true,qid),(gen_random_uuid(),'279',false,qid),(gen_random_uuid(),'299',false,qid),(gen_random_uuid(),'269',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'cbrt(125) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'5',true,qid),(gen_random_uuid(),'25',false,qid),(gen_random_uuid(),'6',false,qid),(gen_random_uuid(),'4',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'6! = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'720',true,qid),(gen_random_uuid(),'120',false,qid),(gen_random_uuid(),'360',false,qid),(gen_random_uuid(),'480',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'log2(64) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'6',true,qid),(gen_random_uuid(),'4',false,qid),(gen_random_uuid(),'8',false,qid),(gen_random_uuid(),'5',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'tan(45) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'1',true,qid),(gen_random_uuid(),'0',false,qid),(gen_random_uuid(),'1.41',false,qid),(gen_random_uuid(),'2',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'sin(30) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'0.5',true,qid),(gen_random_uuid(),'1',false,qid),(gen_random_uuid(),'0',false,qid),(gen_random_uuid(),'0.87',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'13^2 = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'169',true,qid),(gen_random_uuid(),'159',false,qid),(gen_random_uuid(),'179',false,qid),(gen_random_uuid(),'149',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'cbrt(1000) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'10',true,qid),(gen_random_uuid(),'100',false,qid),(gen_random_uuid(),'31',false,qid),(gen_random_uuid(),'32',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'7!/5! = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'42',true,qid),(gen_random_uuid(),'21',false,qid),(gen_random_uuid(),'56',false,qid),(gen_random_uuid(),'35',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'log10(10000) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'4',true,qid),(gen_random_uuid(),'3',false,qid),(gen_random_uuid(),'5',false,qid),(gen_random_uuid(),'2',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'cos(60) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'0.5',true,qid),(gen_random_uuid(),'1',false,qid),(gen_random_uuid(),'0',false,qid),(gen_random_uuid(),'0.87',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'sin(45) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'0.71',true,qid),(gen_random_uuid(),'1',false,qid),(gen_random_uuid(),'0.5',false,qid),(gen_random_uuid(),'0.87',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'19^2 = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'361',true,qid),(gen_random_uuid(),'351',false,qid),(gen_random_uuid(),'371',false,qid),(gen_random_uuid(),'341',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'2^9 = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'512',true,qid),(gen_random_uuid(),'256',false,qid),(gen_random_uuid(),'1024',false,qid),(gen_random_uuid(),'128',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'cbrt(216) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'6',true,qid),(gen_random_uuid(),'36',false,qid),(gen_random_uuid(),'7',false,qid),(gen_random_uuid(),'8',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'8!/6! = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'56',true,qid),(gen_random_uuid(),'28',false,qid),(gen_random_uuid(),'42',false,qid),(gen_random_uuid(),'72',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'log2(256) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'8',true,qid),(gen_random_uuid(),'6',false,qid),(gen_random_uuid(),'7',false,qid),(gen_random_uuid(),'9',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'tan(60) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'1.73',true,qid),(gen_random_uuid(),'1',false,qid),(gen_random_uuid(),'2',false,qid),(gen_random_uuid(),'1.41',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'21^2 = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'441',true,qid),(gen_random_uuid(),'431',false,qid),(gen_random_uuid(),'451',false,qid),(gen_random_uuid(),'421',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'3^5 = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'243',true,qid),(gen_random_uuid(),'81',false,qid),(gen_random_uuid(),'729',false,qid),(gen_random_uuid(),'162',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'cbrt(512) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'8',true,qid),(gen_random_uuid(),'64',false,qid),(gen_random_uuid(),'9',false,qid),(gen_random_uuid(),'7',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'log10(100000) = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'5',true,qid),(gen_random_uuid(),'4',false,qid),(gen_random_uuid(),'6',false,qid),(gen_random_uuid(),'3',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'23^2 = ?',NULL,'Hard',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'529',true,qid),(gen_random_uuid(),'519',false,qid),(gen_random_uuid(),'539',false,qid),(gen_random_uuid(),'509',false,qid);
END $$;
