DO $$
DECLARE
    tid UUID := '019b368e-b3ab-7212-8122-409d91a3befc';
    sid UUID := '019b367b-68f5-7c0c-b100-08a3e8dcc5a1';
    qid UUID;
BEGIN
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'5 - 2 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'3',true,qid),(gen_random_uuid(),'2',false,qid),(gen_random_uuid(),'4',false,qid),(gen_random_uuid(),'1',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'3 * 2 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'6',true,qid),(gen_random_uuid(),'5',false,qid),(gen_random_uuid(),'4',false,qid),(gen_random_uuid(),'8',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'8 / 2 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'4',true,qid),(gen_random_uuid(),'3',false,qid),(gen_random_uuid(),'5',false,qid),(gen_random_uuid(),'6',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'10 + 5 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'15',true,qid),(gen_random_uuid(),'14',false,qid),(gen_random_uuid(),'16',false,qid),(gen_random_uuid(),'12',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'7 - 4 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'3',true,qid),(gen_random_uuid(),'2',false,qid),(gen_random_uuid(),'4',false,qid),(gen_random_uuid(),'5',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'4 * 3 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'12',true,qid),(gen_random_uuid(),'10',false,qid),(gen_random_uuid(),'14',false,qid),(gen_random_uuid(),'11',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'9 / 3 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'3',true,qid),(gen_random_uuid(),'2',false,qid),(gen_random_uuid(),'4',false,qid),(gen_random_uuid(),'6',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'6 + 7 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'13',true,qid),(gen_random_uuid(),'12',false,qid),(gen_random_uuid(),'14',false,qid),(gen_random_uuid(),'11',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'15 - 8 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'7',true,qid),(gen_random_uuid(),'6',false,qid),(gen_random_uuid(),'8',false,qid),(gen_random_uuid(),'9',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'5 * 5 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'25',true,qid),(gen_random_uuid(),'20',false,qid),(gen_random_uuid(),'30',false,qid),(gen_random_uuid(),'15',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'20 / 4 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'5',true,qid),(gen_random_uuid(),'4',false,qid),(gen_random_uuid(),'6',false,qid),(gen_random_uuid(),'8',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'11 + 9 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'20',true,qid),(gen_random_uuid(),'19',false,qid),(gen_random_uuid(),'21',false,qid),(gen_random_uuid(),'18',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'18 - 9 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'9',true,qid),(gen_random_uuid(),'8',false,qid),(gen_random_uuid(),'10',false,qid),(gen_random_uuid(),'7',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'6 * 4 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'24',true,qid),(gen_random_uuid(),'22',false,qid),(gen_random_uuid(),'26',false,qid),(gen_random_uuid(),'20',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'16 / 4 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'4',true,qid),(gen_random_uuid(),'3',false,qid),(gen_random_uuid(),'5',false,qid),(gen_random_uuid(),'6',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'8 + 8 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'16',true,qid),(gen_random_uuid(),'15',false,qid),(gen_random_uuid(),'17',false,qid),(gen_random_uuid(),'14',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'20 - 12 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'8',true,qid),(gen_random_uuid(),'7',false,qid),(gen_random_uuid(),'9',false,qid),(gen_random_uuid(),'10',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'7 * 3 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'21',true,qid),(gen_random_uuid(),'20',false,qid),(gen_random_uuid(),'22',false,qid),(gen_random_uuid(),'18',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'30 / 5 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'6',true,qid),(gen_random_uuid(),'5',false,qid),(gen_random_uuid(),'7',false,qid),(gen_random_uuid(),'8',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'14 + 6 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'20',true,qid),(gen_random_uuid(),'19',false,qid),(gen_random_uuid(),'21',false,qid),(gen_random_uuid(),'18',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'25 - 10 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'15',true,qid),(gen_random_uuid(),'14',false,qid),(gen_random_uuid(),'16',false,qid),(gen_random_uuid(),'13',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'8 * 2 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'16',true,qid),(gen_random_uuid(),'14',false,qid),(gen_random_uuid(),'18',false,qid),(gen_random_uuid(),'12',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'24 / 6 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'4',true,qid),(gen_random_uuid(),'3',false,qid),(gen_random_uuid(),'5',false,qid),(gen_random_uuid(),'6',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'9 + 11 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'20',true,qid),(gen_random_uuid(),'19',false,qid),(gen_random_uuid(),'21',false,qid),(gen_random_uuid(),'18',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'30 - 15 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'15',true,qid),(gen_random_uuid(),'14',false,qid),(gen_random_uuid(),'16',false,qid),(gen_random_uuid(),'13',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'9 * 2 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'18',true,qid),(gen_random_uuid(),'16',false,qid),(gen_random_uuid(),'20',false,qid),(gen_random_uuid(),'14',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'36 / 6 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'6',true,qid),(gen_random_uuid(),'5',false,qid),(gen_random_uuid(),'7',false,qid),(gen_random_uuid(),'8',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'12 + 13 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'25',true,qid),(gen_random_uuid(),'24',false,qid),(gen_random_uuid(),'26',false,qid),(gen_random_uuid(),'23',false,qid);
    qid := gen_random_uuid(); INSERT INTO "Question" ("Id","QuestionText","ImageUrl","Level","TopicId","SubjectId") VALUES (qid,'50 - 25 = ?',NULL,'Easy',tid,sid); INSERT INTO "Answers" ("Id","AnswerText","IsCorrect","QuestionId") VALUES (gen_random_uuid(),'25',true,qid),(gen_random_uuid(),'24',false,qid),(gen_random_uuid(),'26',false,qid),(gen_random_uuid(),'20',false,qid);
END $$;
